### ISSUE TITLE
Using negative numbers causes ChatCmdBuilder to say "No matches"?

### ISSUE THREAD

**Issue by Nukiloco** [rubenwardy/ChatCmdBuilder#3]
What the title says. I have no mods installed other than mine which I'm working with.
The piece of code that does this is the "removenode" sub command. It does work but inputting any negative numbers in x, y, or z will cause it to print "No matches" in the console causing the command not to run. I tried surrounded the x, y, z with ( ) but still has the same results.

I then tried changing :pos:pos to :test:pos, with anything that says pos to test and still says "No matches".

Not sure if this its my code acting up or if its a glitch with the mod. Thanks for reading this!

```
ChatCmdBuilder.new("fmod", function(cmd)

  cmd:sub("removenode :pos:pos", function(name, pos)
    nodedigged = minetest.dig_node(pos)
    return true, tostring(nodedigged)
  end)

  cmd:sub("gametime", function()
    local mttime = minetest.get_gametime()
    return true, mttime
  end)

  cmd:sub("second", function()
    local second = os.date("%S")
    return true, second
  end)

  cmd:sub("help", function()
    return true, "Help!"
  end)

end, {
  description = "Flair's Mod!",
  privs = {
    interact = true
  }
})
```

**Comment by rubenwardy** [comment]
Hopefully this should fix it: https://github.com/rubenwardy/ChatCmdBuilder/commit/c9c0605e0af205976432e033425e653e9aef69bd

**Comment by rubenwardy** [comment]
Fixed
